### DISCUSSION TITLE
Docker Compose Override

### DISCUSSION THREAD

**Discussion by dominik-radulay** [fleetbase/fleetbase#324] [Q&A]
Hi,

I'm not sure if I'm doing something wrong but when I reconfigure appropriate URLs in "docker-compose.override.yml" as recommended during the installation, the website still keeps pointing to the "localhost".

Here is my file:

```
version: '3.8'

services:
  application:
    environment:
      OSRM_HOST: https://router.project-osrm.org
      CONSOLE_HOST: http://192.168.1.183:4200
      APP_URL: http://192.168.1.183:8000/
      SESSION_DOMAIN: 192.168.1.183

  console:
    environment:
      API_HOST: 192.168.1.183:8000
      SOCKETCLUSTER_PORT: 38000
      SOCKETCLUSTER_HOST: 192.168.1.183

  httpd:
    environment:
      NGINX_APPLICATION_HOSTNAME: 192.168.1.183

```
