### ISSUE TITLE
Failing to register new user after Docker setup

### ISSUE THREAD

**Issue by chibsta** [fleetbase/fleetbase#289]
Hi,

After following the Docker installation instructions on Ubuntu 24.04 as well as additional instructions for CORS and SSL, I am unable to create a new account and I get the following errors in my browser console:

Uncaught (in promise) Error: Error processing response: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at parseJSON (fetch.js:268:1)

followed by:

WebSocket connection to 'wss://[mydomain]:38000/socketcluster/' failed: 

* where [mydomain] the fqdn for my server.

### **My .env.development looks like:**

```
API_HOST=https://[mydomain] 
API_NAMESPACE=int/v1
SOCKETCLUSTER_PATH=/socketcluster/
SOCKETCLUSTER_HOST=[mydomain]
SOCKETCLUSTER_SECURE=true
SOCKETCLUSTER_PORT=38000
OSRM_HOST=https://router.project-osrm.org
```

### **My api/config/cors.php looks like:**

```
<?php
use Fleetbase\Support\Utils;
return [
    /*
    |--------------------------------------------------------------------------
    | Cross-Origin Resource Sharing (CORS) Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure your settings for cross-origin resource sharing
    | or "CORS". This determines what cross-origin operations may execute
    | in web browsers. You are free to adjust these settings as needed.
    |
    | To learn more: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
    |
    */

    'paths' => ['*', 'sanctum/csrf-cookie'],
    'allowed_methods' => ['*'],
    'allowed_origins' => array_filter(['fleetbase.sourcelever.com', env('CONSOLE_HOST'), Utils::addWwwToUrl(env('CONSOLE_HOST'))]),
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => ['x-compressed-json', 'access-console-sandbox', 'access-console-sandbox-key'],
    'max_age' => 0,
    'supports_credentials' => false,
];
```

### **My docker-compose.override.yml looks like:**

```
services:
  cache:
    image: redis:4-alpine

  database:
    image: mysql:8.0-oracle
    ports:
      - "3306:3306"
    volumes:
      - "./docker/database/:/docker-entrypoint-initdb.d/"
      - "./docker/database/mysql:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "fleetbase"

  socket:
    image: socketcluster/socketcluster:v17.4.0
    ports:
      - "38000:8000"
    environment:
      SOCKETCLUSTER_WORKERS: 10
      SOCKETCLUSTER_BROKERS: 10

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: events-dev
      args:
        ENVIRONMENT: development
    environment:
      DATABASE_URL: "mysql://root@database/fleetbase"
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      CACHE_PATH: /fleetbase/api/storage/framework/cache
      CACHE_URL: tcp://cache
      REDIS_URL: tcp://cache
  console:
    build:
      context: . 
      dockerfile: console/Dockerfile.server-build
      args:
        ENVIRONMENT: development
    ports:
      - "4200:4200"
      - "443:443"
    volumes:
      - console-build:/console
      - /etc/letsencrypt/live/[mydomain]/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/[mydomain]/privkey.pem:/etc/ssl/private/privkey.pem

    environment:
      - SSL_CERTIFICATE=/etc/ssl/certs/fullchain.pem
      - SSL_CERTIFICATE_KEY=/etc/ssl/private/privkey.pem

  application:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app-dev
      args:
        ENVIRONMENT: development
        GITHUB_AUTH_KEY: ${GITHUB_AUTH_KEY}
    volumes:
      - console-build:/fleetbase/console
    environment:
      ENVIRONMENT: development
      DATABASE_URL: "mysql://root@database/fleetbase"
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      CACHE_PATH: /fleetbase/api/storage/framework/cache
      CACHE_URL: tcp://cache
      REDIS_URL: tcp://cache
      SESSION_DOMAIN: [mydomain]
      BROADCAST_DRIVER: socketcluster
      MAIL_FROM_NAME: Fleetbase
      APP_NAME: Fleetbase
      CONSOLE_HOST: http://[mydomain]:4200
      LOG_CHANNEL: daily
      MODEL_CACHE_ENABLED: 'true'
      RESPONSE_CACHE_ENABLED: 'true'
      RESPONSE_CACHE_DRIVER: redis
      REGISTRY_HOST: https://registry.fleetbase.io
      REGISTRY_PREINSTALLED_EXTENSIONS: 'true'
      OSRM_HOST: https://router.project-osrm.org
    depends_on:
      - database
      - cache
      - queue

  httpd:
    build:
      context: .
      dockerfile: docker/httpd/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - application

volumes:
  console-build:
```

### **My console/nginx.conf:**

```
#server {
#    listen       4200;
#    server_name  [mydomain];
#
#    location / {
#        root   /usr/share/nginx/html;
#        try_files $uri $uri/ /index.html =404;
#    }
#}

server {
    listen          443 ssl;
    server_name     [mydomain];
#    return          301 https://$host$request_uri;

    ssl_certificate     /etc/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/privkey.pem;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html =404;
    }
}
```

My expectation is that with CORS and SSL configured I should be able to register a new user and start using my Fleetbase instance. I have added a screenshot of what I seeing on the screen, if this helps, below. 

![Screenshot from 2024-08-09 16-54-48](https://github.com/user-attachments/assets/93f2790a-f4c1-40e9-89cb-6e7d4bcbb819)

In another issue in the forum I noted that API_HOST should be configured as:

API_HOST=[mydomain]:8000

However, with this setting, I am not clear how to configure SSL/TLS for the API. SSL for the console was relatively easier to figure out but I do not know where I would put the Nginx configuration for the API.

Kindly assist.
