### ISSUE TITLE
How to deploy fleetbase behind treafik reverse proxy?

### ISSUE THREAD

**Issue by Fernien** [fleetbase/fleetbase#322]
Hello together,

i've tried setting up fleetbase behind a traefik reverse proxy but i cant really find out how to do it.
First i noticed that there is an APP_KEY needed in the application service thats not mentioned in the documentation.
Afterwards i managed to access the console page but there are a lot of errors inside the browser console i don't fully understand since i changed all the URLs via einvironment variables and at least expect the requested urls to change too.
![image](https://github.com/user-attachments/assets/c2dac352-c811-4aff-88d1-0fc3695992e5)

Here is my docker-compose.override.yml, hopefully someone has some tips for correctly setting up fleetbase behind traefik. Pretty sure there needs to be some configuration change for the socket part and the api part.

```
x-vars: &vars
   environment:
      - APP_URL=https://fleetbase.example.com
      - API_HOST=http://httpd:8000
      - CONSOLE_HOST=https://fleetbase.example.com
      - SOCKETCLUSTER_HOST=fleetbase.example.com

networks:
   traefik-public:
      external: true
   internal:
      name: internal

services:
  application:
    <<: *vars
    networks:
      - internal
    environment:
      - APP_KEY=base64:0ASIWI+shOgDdLCx+QcSpBD2gLfVd1Zekx+Os6JaWNE=
      - MAIL_MAILER=SMTP
      - DATABASE_URL=mysql://root:supersecurepassword@database:3306/fleetbase
      - REDIS_URL=redis://redis:6379

  httpd:
    <<: *vars
    networks:
      - internal

  console:
    <<: *vars
    networks:
      - internal
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fleetbase.loadbalancer.server.port=4200"
      - "traefik.http.routers.fleetbase-secured.entrypoints=websecure"
      - "traefik.http.routers.fleetbase-secured.rule=Host(`fleetbase.example.com`)"
      - "traefik.http.routers.fleetbase-secured.tls=true"

  queue:
    <<: *vars
    environment:
      - DATABASE_URL=mysql://root:supersecurepassword@database:3306/fleetbase
    networks:
      - internal

  socket:
    <<: *vars
    networks:
      - internal

  cache:
    <<: *vars
    networks:
      - internal

  database:
    <<: *vars
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=supersecurepassword
```

The treafik-public network is facing to the internet whilst the internal is only for traffic between the containers itself.
